/**
 * World-specific unique collectibles catalogue.
 * Each world has its signature item with distinct visual model, name, value,
 * and mapped usable SUPERPOWER ability!
 */
import type { PowerUpType } from './powerups.config';

export interface WorldCollectibleDef {
  id: string;
  worldId: string;
  name: string;
  category: string;
  color: number;
  glowColor: number;
  emissive: number;
  bonusCoins: number;
  powerType: PowerUpType;
  description: string;
  shape: 'crystal' | 'cell' | 'scarab' | 'chip' | 'pearl' | 'leaf' | 'gear' | 'coin' | 'seed' | 'crown' | 'map' | 'coral' | 'fragment' | 'plasma' | 'star' | 'feather';
}

export const WORLD_COLLECTIBLES: Record<string, WorldCollectibleDef> = {
  city: {
    id: 'energy_cell',
    worldId: 'city',
    name: 'Energy Cell',
    category: 'tech',
    color: 0x38e1ff,
    glowColor: 0x00f0ff,
    emissive: 0x006688,
    bonusCoins: 5,
    powerType: 'dash',
    description: 'High-voltage power cell granting instant Sonic Dash across lanes.',
    shape: 'cell',
  },
  jungle: {
    id: 'jungle_gem',
    worldId: 'jungle',
    name: 'Jungle Gem',
    category: 'relic',
    color: 0x2ecc71,
    glowColor: 0x27ae60,
    emissive: 0x005522,
    bonusCoins: 6,
    powerType: 'double_jump',
    description: 'Ancient emerald stone granting Double Hop to leap over obstacles.',
    shape: 'crystal',
  },
  desert: {
    id: 'scarab',
    worldId: 'desert',
    name: 'Golden Scarab',
    category: 'relic',
    color: 0xf1c40f,
    glowColor: 0xffd700,
    emissive: 0x554400,
    bonusCoins: 7,
    powerType: 'magnet',
    description: 'Sacred golden amulet magnetically drawing all nearby coins to your hero.',
    shape: 'scarab',
  },
  snow: {
    id: 'ice_crystal',
    worldId: 'snow',
    name: 'Ice Crystal',
    category: 'mineral',
    color: 0xa8d8ea,
    glowColor: 0xdff9fb,
    emissive: 0x224466,
    bonusCoins: 6,
    powerType: 'freeze',
    description: 'Permafrost prism that freezes all traffic and hazards in place.',
    shape: 'crystal',
  },
  neon: {
    id: 'data_chip',
    worldId: 'neon',
    name: 'Data Chip',
    category: 'tech',
    color: 0xff3fb4,
    glowColor: 0xff70a6,
    emissive: 0x660044,
    bonusCoins: 8,
    powerType: 'time_warp',
    description: 'Quantum memory chip that slows world traffic by 65%.',
    shape: 'chip',
  },
  volcano: {
    id: 'magma_crystal',
    worldId: 'volcano',
    name: 'Magma Crystal',
    category: 'mineral',
    color: 0xff5252,
    glowColor: 0xff793f,
    emissive: 0x771100,
    bonusCoins: 9,
    powerType: 'fire_shield',
    description: 'Obsidian core creating a Heat Shield that absorbs collision damage.',
    shape: 'crystal',
  },
  beach: {
    id: 'pearl',
    worldId: 'beach',
    name: 'Ocean Pearl',
    category: 'nature',
    color: 0xfff0f5,
    glowColor: 0xfaf0e6,
    emissive: 0x443333,
    bonusCoins: 6,
    powerType: 'shield',
    description: 'Iridescent pearl creating a Force Shield barrier against traffic.',
    shape: 'pearl',
  },
  forest: {
    id: 'magic_leaf',
    worldId: 'forest',
    name: 'Magic Leaf',
    category: 'nature',
    color: 0x7bed9f,
    glowColor: 0x2ed573,
    emissive: 0x004422,
    bonusCoins: 7,
    powerType: 'ghost',
    description: 'Phosphorescent woodland leaf enabling Phase Ghost mode through cars.',
    shape: 'leaf',
  },
  industrial: {
    id: 'power_gear',
    worldId: 'industrial',
    name: 'Titanium Gear',
    category: 'tech',
    color: 0xffa502,
    glowColor: 0xe67e22,
    emissive: 0x442200,
    bonusCoins: 7,
    powerType: 'magnet',
    description: 'Industrial cog emitting magnetic field pulling coins directly to you.',
    shape: 'gear',
  },
  temple: {
    id: 'ancient_coin',
    worldId: 'temple',
    name: 'Ancient Rune Coin',
    category: 'relic',
    color: 0xe056fd,
    glowColor: 0xbe2edd,
    emissive: 0x440055,
    bonusCoins: 8,
    powerType: 'time_warp',
    description: 'Guardian ward coin slowing world time flow for easy dodging.',
    shape: 'coin',
  },
  flooded: {
    id: 'water_crystal',
    worldId: 'flooded',
    name: 'Water Crystal',
    category: 'mineral',
    color: 0x00d2d3,
    glowColor: 0x48dbfb,
    emissive: 0x003344,
    bonusCoins: 7,
    powerType: 'freeze',
    description: 'Tidal crystal that freezes road traffic and boat hazards solid.',
    shape: 'crystal',
  },
  railway: {
    id: 'rail_token',
    worldId: 'railway',
    name: 'Brass Rail Token',
    category: 'relic',
    color: 0xf6b93b,
    glowColor: 0xe55039,
    emissive: 0x442211,
    bonusCoins: 8,
    powerType: 'dash',
    description: 'Conductor token granting high-speed Sonic Dash across rail lines.',
    shape: 'coin',
  },
  countryside: {
    id: 'golden_seed',
    worldId: 'countryside',
    name: 'Golden Seed',
    category: 'nature',
    color: 0x78e08f,
    glowColor: 0x38ada9,
    emissive: 0x113311,
    bonusCoins: 6,
    powerType: 'magnet',
    description: 'Luminous agrarian seed pulling all gold coins to your hero.',
    shape: 'seed',
  },
  mountain: {
    id: 'mountain_crystal',
    worldId: 'mountain',
    name: 'Summit Quartz',
    category: 'mineral',
    color: 0x82ccdd,
    glowColor: 0x60a3bc,
    emissive: 0x112233,
    bonusCoins: 8,
    powerType: 'double_jump',
    description: 'Alpine quartz allowing mighty leaps over rocks and vehicles.',
    shape: 'crystal',
  },
  fantasy: {
    id: 'crown_jewel',
    worldId: 'fantasy',
    name: 'Royal Crown',
    category: 'relic',
    color: 0xf8c291,
    glowColor: 0xe77f67,
    emissive: 0x552211,
    bonusCoins: 10,
    powerType: 'shield',
    description: 'Royal enchanted coronet shielding the hero from fatal strikes.',
    shape: 'crown',
  },
  pirate: {
    id: 'pirate_map',
    worldId: 'pirate',
    name: 'Pirate Map Scroll',
    category: 'relic',
    color: 0xd6a2e8,
    glowColor: 0x82589f,
    emissive: 0x331144,
    bonusCoins: 9,
    powerType: 'dash',
    description: 'Ancient treasure chart powering a rapid sprint past cannon carts.',
    shape: 'map',
  },
  ocean: {
    id: 'sea_coral',
    worldId: 'ocean',
    name: 'Luminescent Coral',
    category: 'nature',
    color: 0xff6b81,
    glowColor: 0xff4757,
    emissive: 0x551122,
    bonusCoins: 8,
    powerType: 'freeze',
    description: 'Deep sea living coral instantly freezing moving obstacles.',
    shape: 'coral',
  },
  moon: {
    id: 'lunar_fragment',
    worldId: 'moon',
    name: 'Lunar Fragment',
    category: 'mineral',
    color: 0xced6e0,
    glowColor: 0xf1f2f6,
    emissive: 0x2f3542,
    bonusCoins: 10,
    powerType: 'low_gravity',
    description: 'Zero-gravity lunar rock granting soaring multi-lane leaps.',
    shape: 'fragment',
  },
  sky: {
    id: 'sky_crystal',
    worldId: 'sky',
    name: 'Aether Crystal',
    category: 'mineral',
    color: 0x70a1ff,
    glowColor: 0x1e90ff,
    emissive: 0x002266,
    bonusCoins: 10,
    powerType: 'time_warp',
    description: 'High-altitude aether shard slowing down aerial and ground traffic.',
    shape: 'crystal',
  },
  alien: {
    id: 'plasma_crystal',
    worldId: 'alien',
    name: 'Plasma Core',
    category: 'tech',
    color: 0xa55eea,
    glowColor: 0x8854d0,
    emissive: 0x381768,
    bonusCoins: 12,
    powerType: 'ghost',
    description: 'Alien singularity allowing phase shifting directly through UFOs.',
    shape: 'plasma',
  },
};

export function collectibleForWorld(worldId: string): WorldCollectibleDef {
  return WORLD_COLLECTIBLES[worldId.toLowerCase()] ?? WORLD_COLLECTIBLES.city;
}
