/**
 * World-specific unique collectibles catalogue.
 * Each world has its signature item with distinct visual model, name, and value.
 */

export interface WorldCollectibleDef {
  id: string;
  worldId: string;
  name: string;
  category: string;
  color: number;
  glowColor: number;
  emissive: number;
  bonusCoins: number;
  description: string;
  shape: 'crystal' | 'cell' | 'scarab' | 'chip' | 'pearl' | 'leaf' | 'gear' | 'coin' | 'seed' | 'crown' | 'map' | 'coral' | 'fragment' | 'plasma';
}

export const WORLD_COLLECTIBLES: Record<string, WorldCollectibleDef> = {
  city: {
    id: 'energy_cell',
    worldId: 'city',
    name: 'Energy Cell',
    category: 'tech',
    color: 0x38e1ff,
    glowColor: 0x00f0ff,
    emissive: 0x006688,
    bonusCoins: 5,
    description: 'A compact high-voltage power cell discarded by city delivery bots.',
    shape: 'cell',
  },
  jungle: {
    id: 'jungle_gem',
    worldId: 'jungle',
    name: 'Jungle Gem',
    category: 'relic',
    color: 0x2ecc71,
    glowColor: 0x27ae60,
    emissive: 0x005522,
    bonusCoins: 6,
    description: 'An ancient emerald stone glowing with tropical life force.',
    shape: 'crystal',
  },
  desert: {
    id: 'scarab',
    worldId: 'desert',
    name: 'Golden Scarab',
    category: 'relic',
    color: 0xf1c40f,
    glowColor: 0xffd700,
    emissive: 0x554400,
    bonusCoins: 7,
    description: 'A sacred golden beetle amulet preserved in desert sands.',
    shape: 'scarab',
  },
  snow: {
    id: 'ice_crystal',
    worldId: 'snow',
    name: 'Ice Crystal',
    category: 'mineral',
    color: 0xa8d8ea,
    glowColor: 0xdff9fb,
    emissive: 0x224466,
    bonusCoins: 6,
    description: 'A prism of eternal permafrost that never melts.',
    shape: 'crystal',
  },
  neon: {
    id: 'data_chip',
    worldId: 'neon',
    name: 'Data Chip',
    category: 'tech',
    color: 0xff3fb4,
    glowColor: 0xff70a6,
    emissive: 0x660044,
    bonusCoins: 8,
    description: 'An encrypted quantum memory unit loaded with cyber secrets.',
    shape: 'chip',
  },
  volcano: {
    id: 'magma_crystal',
    worldId: 'volcano',
    name: 'Magma Crystal',
    category: 'mineral',
    color: 0xff5252,
    glowColor: 0xff793f,
    emissive: 0x771100,
    bonusCoins: 9,
    description: 'Solidified obsidian crust pulsating with active subterranean heat.',
    shape: 'crystal',
  },
  beach: {
    id: 'pearl',
    worldId: 'beach',
    name: 'Ocean Pearl',
    category: 'nature',
    color: 0xfff0f5,
    glowColor: 0xfaf0e6,
    emissive: 0x443333,
    bonusCoins: 6,
    description: 'An iridescent luminous pearl washed ashore from the coral reef.',
    shape: 'pearl',
  },
  forest: {
    id: 'magic_leaf',
    worldId: 'forest',
    name: 'Magic Leaf',
    category: 'nature',
    color: 0x7bed9f,
    glowColor: 0x2ed573,
    emissive: 0x004422,
    bonusCoins: 7,
    description: 'A phosphorescent leaf blessed by woodland spirits.',
    shape: 'leaf',
  },
  industrial: {
    id: 'power_gear',
    worldId: 'industrial',
    name: 'Titanium Gear',
    category: 'tech',
    color: 0xffa502,
    glowColor: 0xe67e22,
    emissive: 0x442200,
    bonusCoins: 7,
    description: 'Precision industrial cog salvaged from automated assembly lines.',
    shape: 'gear',
  },
  temple: {
    id: 'ancient_coin',
    worldId: 'temple',
    name: 'Ancient Rune Coin',
    category: 'relic',
    color: 0xe056fd,
    glowColor: 0xbe2edd,
    emissive: 0x440055,
    bonusCoins: 8,
    description: 'A carved stone coin engraved with temple guardian wards.',
    shape: 'coin',
  },
  flooded: {
    id: 'water_crystal',
    worldId: 'flooded',
    name: 'Water Crystal',
    category: 'mineral',
    color: 0x00d2d3,
    glowColor: 0x48dbfb,
    emissive: 0x003344,
    bonusCoins: 7,
    description: 'Pure crystallized tidal water condensed under submerged ruins.',
    shape: 'crystal',
  },
  railway: {
    id: 'rail_token',
    worldId: 'railway',
    name: 'Brass Rail Token',
    category: 'relic',
    color: 0xf6b93b,
    glowColor: 0xe55039,
    emissive: 0x442211,
    bonusCoins: 8,
    description: 'An antique conductor token granting passage through mountain tunnels.',
    shape: 'coin',
  },
  countryside: {
    id: 'golden_seed',
    worldId: 'countryside',
    name: 'Golden Seed',
    category: 'nature',
    color: 0x78e08f,
    glowColor: 0x38ada9,
    emissive: 0x113311,
    bonusCoins: 6,
    description: 'A miraculously fertile seed that glows under sunlight.',
    shape: 'seed',
  },
  mountain: {
    id: 'mountain_crystal',
    worldId: 'mountain',
    name: 'Summit Quartz',
    category: 'mineral',
    color: 0x82ccdd,
    glowColor: 0x60a3bc,
    emissive: 0x112233,
    bonusCoins: 8,
    description: 'High-altitude crystalline shard forged amidst freezing gale winds.',
    shape: 'crystal',
  },
  fantasy: {
    id: 'crown_jewel',
    worldId: 'fantasy',
    name: 'Royal Crown',
    category: 'relic',
    color: 0xf8c291,
    glowColor: 0xe77f67,
    emissive: 0x552211,
    bonusCoins: 10,
    description: 'A miniature jewel-encrusted coronet lost during castle defense.',
    shape: 'crown',
  },
  pirate: {
    id: 'pirate_map',
    worldId: 'pirate',
    name: 'Pirate Map Scroll',
    category: 'relic',
    color: 0xd6a2e8,
    glowColor: 0x82589f,
    emissive: 0x331144,
    bonusCoins: 9,
    description: 'A parchment chart marking buried treasure chests across the archipelago.',
    shape: 'map',
  },
  ocean: {
    id: 'sea_coral',
    worldId: 'ocean',
    name: 'Luminescent Coral',
    category: 'nature',
    color: 0xff6b81,
    glowColor: 0xff4757,
    emissive: 0x551122,
    bonusCoins: 8,
    description: 'Living branch of bioluminescent deep sea reef.',
    shape: 'coral',
  },
  moon: {
    id: 'lunar_fragment',
    worldId: 'moon',
    name: 'Lunar Fragment',
    category: 'mineral',
    color: 0xced6e0,
    glowColor: 0xf1f2f6,
    emissive: 0x2f3542,
    bonusCoins: 10,
    description: 'An exotic moon rock sample containing traces of zero-gravity helium.',
    shape: 'fragment',
  },
  sky: {
    id: 'sky_crystal',
    worldId: 'sky',
    name: 'Aether Crystal',
    category: 'mineral',
    color: 0x70a1ff,
    glowColor: 0x1e90ff,
    emissive: 0x002266,
    bonusCoins: 10,
    description: 'A floating crystalline shard suspended by skyward thermals.',
    shape: 'crystal',
  },
  alien: {
    id: 'plasma_crystal',
    worldId: 'alien',
    name: 'Plasma Core',
    category: 'tech',
    color: 0xa55eea,
    glowColor: 0x8854d0,
    emissive: 0x381768,
    bonusCoins: 12,
    description: 'A pulsing extraterrestrial singularity capable of bending spacetime.',
    shape: 'plasma',
  },
};

export function collectibleForWorld(worldId: string): WorldCollectibleDef {
  return WORLD_COLLECTIBLES[worldId.toLowerCase()] ?? WORLD_COLLECTIBLES.city;
}
