/**
 * Signature world events catalogue for all 20 worlds.
 * Each event provides readable telegraphing (warning banner + sound cue + visual effect)
 * and fair, reversible gameplay influence.
 */

export interface WorldEventDef {
  id: string;
  worldId: string;
  title: string;
  subtitle: string;
  warningDurationMs: number;
  activeDurationMs: number;
  cooldownLanes: number;
  effectType: 'rush' | 'particles' | 'lighting' | 'hazard' | 'surge';
  color: number;
  intensity: number;
}

export const WORLD_EVENTS: Record<string, WorldEventDef> = {
  city: {
    id: 'rush_hour',
    worldId: 'city',
    title: 'RUSH HOUR!',
    subtitle: 'HEAVY TRAFFIC INCOMING · WATCH BOTH WAYS',
    warningDurationMs: 1800,
    activeDurationMs: 6500,
    cooldownLanes: 35,
    effectType: 'rush',
    color: 0xffc93c,
    intensity: 1.25,
  },
  jungle: {
    id: 'river_surge',
    worldId: 'jungle',
    title: 'RIVER SURGE!',
    subtitle: 'RIVER CURRENTS RISING · WATCH WOODEN PLANKS',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'surge',
    color: 0x3fa8d8,
    intensity: 1.2,
  },
  desert: {
    id: 'sandstorm',
    worldId: 'desert',
    title: 'SANDSTORM!',
    subtitle: 'DUST GUSTS RISING · MAINTAIN STEADY HOPS',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'particles',
    color: 0xf5cd79,
    intensity: 1.3,
  },
  snow: {
    id: 'blizzard',
    worldId: 'snow',
    title: 'BLIZZARD!',
    subtitle: 'ZERO VISIBILITY GALE · FROZEN HIGHWAY AHEAD',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'particles',
    color: 0xdff9fb,
    intensity: 1.3,
  },
  neon: {
    id: 'power_outage',
    worldId: 'neon',
    title: 'POWER OUTAGE!',
    subtitle: 'GRID EMERGENCY · TRACK NEON HEADLIGHTS',
    warningDurationMs: 1800,
    activeDurationMs: 5500,
    cooldownLanes: 35,
    effectType: 'lighting',
    color: 0xff3fb4,
    intensity: 1.4,
  },
  volcano: {
    id: 'eruption',
    worldId: 'volcano',
    title: 'ERUPTION WARNING!',
    subtitle: 'MAGMA TREMORS DETECTED · EVACUATE SAFELY',
    warningDurationMs: 2000,
    activeDurationMs: 6500,
    cooldownLanes: 35,
    effectType: 'hazard',
    color: 0xff4757,
    intensity: 1.5,
  },
  beach: {
    id: 'mega_wave',
    worldId: 'beach',
    title: 'MEGA WAVE!',
    subtitle: 'HIGH TIDE SURGE · BOARDWALK CLEARANCE',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'surge',
    color: 0x48dbfb,
    intensity: 1.25,
  },
  forest: {
    id: 'forest_awakening',
    worldId: 'forest',
    title: 'FOREST AWAKENING!',
    subtitle: 'ANCIENT GLOW SPORES IN THE AIR',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'particles',
    color: 0x2ed573,
    intensity: 1.2,
  },
  industrial: {
    id: 'factory_overload',
    worldId: 'industrial',
    title: 'FACTORY OVERLOAD!',
    subtitle: 'STEAM PRESSURE BLOWOUT · CONVOYS ADVANCING',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'rush',
    color: 0xffa502,
    intensity: 1.35,
  },
  temple: {
    id: 'temple_collapse',
    worldId: 'temple',
    title: 'TEMPLE TREMOR!',
    subtitle: 'ANCIENT COLUMNS SHAKING · STEP CAREFULLY',
    warningDurationMs: 2000,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'hazard',
    color: 0xbe2edd,
    intensity: 1.3,
  },
  flooded: {
    id: 'flash_flood',
    worldId: 'flooded',
    title: 'FLASH FLOOD!',
    subtitle: 'SUBMERGED CANALS SWELLING · SEEK HIGHER GROUND',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'surge',
    color: 0x00d2d3,
    intensity: 1.3,
  },
  railway: {
    id: 'train_rush',
    worldId: 'railway',
    title: 'EXPRESS TRAIN RUSH!',
    subtitle: 'MULTIPLE LOCOMOTIVES CROSSING STRETCH',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'rush',
    color: 0xf6b93b,
    intensity: 1.4,
  },
  countryside: {
    id: 'farm_rush',
    worldId: 'countryside',
    title: 'HARVEST RUSH!',
    subtitle: 'TRACTOR FLEETS EN ROUTE TO SILOS',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'rush',
    color: 0x78e08f,
    intensity: 1.2,
  },
  mountain: {
    id: 'avalanche',
    worldId: 'mountain',
    title: 'AVALANCHE ALERT!',
    subtitle: 'POWDER RUNOFF ON UPPER SLOPES',
    warningDurationMs: 2000,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'particles',
    color: 0x82ccdd,
    intensity: 1.4,
  },
  fantasy: {
    id: 'castle_defense',
    worldId: 'fantasy',
    title: 'CASTLE PARADE!',
    subtitle: 'ROYAL GUARD DRILLS IN PROGRESS',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'rush',
    color: 0xf8c291,
    intensity: 1.25,
  },
  pirate: {
    id: 'pirate_raid',
    worldId: 'pirate',
    title: 'PIRATE RAID!',
    subtitle: 'BUCCANEER GALLEONS FLANKING DOCKS',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'hazard',
    color: 0xd6a2e8,
    intensity: 1.35,
  },
  ocean: {
    id: 'tidal_wave',
    worldId: 'ocean',
    title: 'TIDAL SWELL!',
    subtitle: 'DEEP OCEAN CREST WASHING ACROSS LANES',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'surge',
    color: 0x1e90ff,
    intensity: 1.3,
  },
  moon: {
    id: 'meteor_shower',
    worldId: 'moon',
    title: 'METEOR SHOWER!',
    subtitle: 'ORBITAL DEBRIS ENTERING LUNAR ATMOSPHERE',
    warningDurationMs: 2000,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'particles',
    color: 0xced6e0,
    intensity: 1.4,
  },
  sky: {
    id: 'sky_collapse',
    worldId: 'sky',
    title: 'AETHER GUST!',
    subtitle: 'HIGH ALTITUDE THERMALS WHIRLING',
    warningDurationMs: 1800,
    activeDurationMs: 6000,
    cooldownLanes: 35,
    effectType: 'particles',
    color: 0x70a1ff,
    intensity: 1.3,
  },
  alien: {
    id: 'ufo_invasion',
    worldId: 'alien',
    title: 'UFO INVASION!',
    subtitle: 'MOTHERSHIP TRACTOR SWARM DETECTED',
    warningDurationMs: 2000,
    activeDurationMs: 6500,
    cooldownLanes: 35,
    effectType: 'lighting',
    color: 0xa55eea,
    intensity: 1.5,
  },
};

export function eventForWorld(worldId: string): WorldEventDef {
  return WORLD_EVENTS[worldId.toLowerCase()] ?? WORLD_EVENTS.city;
}
